name: Daily Work

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Make changes
        run: |
          mkdir -p contributors
          echo "Commit made at $(date '+%Y-%m-%d %H:%M:%S')" > contributors/log.txt

      - name: Pull latest changes
        run: git pull

      - name: Commit and Push for Multiple Users
        run: |
          # List of users
          users=(
            "862275679@qq.com:omgzui"
            "xianger94@gmail.com:shfshanyue"
            "a0931990604@gmail.com:janice kuo"
            "jefersonb88@gmail.com:Jeferson"
            "name@provider.com:yourGitHubUsername"
            "maxim.oleinik@gmail.com:Maxim Oleinik"
            "happypeter1983@gmail.com:Peter Wang"
            "hamitmizrak@gmail.com:hamitmizrak"
            "park.heekang33@gmail.com:Heekang Park"
            "zhiweik@gmail.com:Chen Zhiwei"
            "benjamescunningham@gmail.com:Ben Cunningham"
            "gmail@hdknr.com:hdknr"
            "benelog@gmail.com:Sanghyuk Jung"
            "gbrouwer5151@gmail.com:Gijs Joost Brouwer"
            "mercedes@gmail.com:Mercedes-benz"
            "lammborghini@gmail.com:Lamborghini"
            "anushkarajput2907@gmail.com:anushka"
            "hansolo@gmail.com:Han Solo"
            "pataraco@gmail.com:Patrick Raco"
            "tai15515@kakao.com:DEVTYPE"
            "Informatik.on.GitHub@gmail.com:DEVTYPE"
            "omajid@redhat.com:DEVTYPE"
            "omair.majid@gmail.com:DEVTYPE"
            "toda.shuta@gmail.com:DEVTYPE"
            "nhphuong91@gmail.com:nhphuong91"
            "minkj1992@gmail.com:minkj1992"
            "awnishmmg.a41@gmail.com:awnish kumar"
            "pico.dev@gmail.com:pico.dev"
            "dantuguf14105@gmail.com:neeraj dantu"
            "vibhordubey333@gmail.com:vibhordubey333"
            "cool21540125@gmail.com:TonyChou"
            "userok.zmina@gmail.com:Alex"
            "maedk10@gmail.com:danielk0121"
            "charlie.robbins@gmail.com:indexzero"
            "jackson.dgmedeiros@gmail.com:jackson.dgmedeiros"
            "manbing3@gmail.com:Manbing"
            "nagcloudlab@gmail.com:Nag"
            "juniormayhe@gmail.com:Junior Mayhe"
            "datasaga@gmail.com:DATASAGA"
            "wangshijun2010@gmail.com:wangshijun"
            "evil756377706@gmail.com:EvilDome1"
            "kevinrue@users.noreply.github.com:Kevin Rue-Albrecht"
            "manishkumarlps41@gmail.com:Manish Kumar"
            "razonyang@gmail.com:razonyang"
            "john.doe@email.com:John Doe"
            "din@mail.com:Ditt Namn"
            "matthew.brett@gmail.com:Matthew Brett"
            "ruifigueira@isa.ulisboa.pt:Rui Figueira"
            "vlad@tran.sylvan.ia:Vlad Dracula"
            "MyEmail@Zoho.com:My Name"
            "lornamichille@hotmail.com:trinity22"
            "manuwasabi@hotmail.com:Lamusica2131"
            "lau-brito@hotmail.com:Mathilde2009"
            "niecievega@hotmail.com:artie927"
            "sapphireblu95@hotmail.com:Vampires95"
            "ldnhlj@hotmail.com:Ljandshiqi60"
            "carlozestbn@hotmail.com:1026sanandres"
            "aprilgulla@hotmail.com:ilm4ksmpggmac"
            "richieodd@outlook.com:Reese1089"
            "tai.nguyen.1656854@hotmail.com:Tai71881"
            "adrian2davis@hotmail.com:Alain2romy$"
            "taylorjordanvball@hotmail.com:Cooper123"
            "jokershadin123@hotmail.com:disc0Shadin"
            "isisphyre79@hotmail.com:NovBell3"
            "gpsamp@outlook.com:GTr141091"
            "llt1876951639@outlook.com:Dt13671367"
            "Tinabetts@outlook.com:Tbetts111"
            "jayhowell1968@hotmail.com:Kubota12"
            "letuan86@live.com:Lt311906"
            "aferdita.cimo@outlook.com:Dita1968"
            "tonyabudinger@hotmail.com:ellaMay20"
            "moyilla7893@hotmail.com:yaswanth7893"
            "tonyaconnochie@hotmail.com:1love4me"
            "jenjen2015.je@hotmail.com:mrpmgp85"
            "mark.dunn45@hotmail.com:Dalton45"
            "guillermocrz490@hotmail.com:memo1985"
            "dann_segovia@hotmail.com:Midlandcapo11"
            "ju.ferneda@outlook.com:Lucyandfraser5"
            "lucas-1660@hotmail.com:Lucas1660"
            "anamarie2621@hotmail.com:west2313"
            "c.hadden84@hotmail.com:mykids08"
            "arthursharon39@hotmail.com:smooth1129"
            "pletnes@hotmail.com:gallagher18"
            "francis.barrios.palacios@hotmail.com:83138073"
            "aaronxiong00@outlook.com:Xiongaaron123"
            "milfordeagle78@hotmail.com:Rb414095"
            "shockey725@hotmail.com:bedroom123"
            "yamaha_zl@hotmail.com:Zl432018"
            "moboussek@hotmail.com:morocco89"
            "dsbook98@hotmail.com:daegi7672"
            "mrodriguezt@live.com:REBELDE89!"
            "Soltkyrakrs@hotmail.com:cedpsrp2125"
            "dlabuguen808@hotmail.com:Laciedel143"
            "josekelso89@hotmail.com:strata21"
            "fabianabcvr@hotmail.com:Fofucha10"
            "gabrieljason2903@outlook.com:Nexius252"
            "oscaart11@hotmail.com:Oscar3072003"
            "indrick.anthony@hotmail.com:ia04271956"
            "shaundrapeterson@hotmail.com:jayshawn123"
            "najjar2626@hotmail.com:tsmn2626"
            "clomp44@hotmail.com:Merve1986"
            "ank.thakur05@hotmail.com:anoop8285530497"
            "michael.devid@hotmail.com:michael1234561"
            "eee8899567@hotmail.com:aa0912105331"
            "stacy.marie942@hotmail.com:QwErTy159"
            "jazmin.pantich@hotmail.com:japari00"
            "pittsburgh0420@hotmail.com:Crunkgoespunk69"
            "brentsaperstein@hotmail.com:Clinton1"
            "debra.rush899@hotmail.com:dragonlady23"
            "mapikaren_love@hotmail.com:Manocho08"
            "aline.beraldo@outlook.com:Beraldo21"
            "vinakartika2000@hotmail.com:menyali2000"
            "pastorbarbararichardson65@hotmail.com:goodwind65"
            "mirnarizka@hotmail.com:112515kyo"
            "gdeleon921@hotmail.com:gmatoby16"
            "buluramir@hotmail.com:amirmahdi13819"
            "sophiewaddell1@hotmail.com:sasha27we"
            "ritaneith31@hotmail.com:anne1957"
            "kennycook602@hotmail.com:kgvb848484"
            "forque239@hotmail.com:2375615F"
            "borjacalfer@hotmail.com:719578Bj"
            "cairi.young@hotmail.com:Mzright1"
            "pedrobotion@hotmail.com:Pepe2912"
            "brandee7522@hotmail.com:Samothsnave69"
            "boobiek1985@hotmail.com:trenda88"
            "bashoukawadee@hotmail.com:MayMook88"
            "s.m.bacon@hotmail.com:smmbacon"
            "kdbl0c@hotmail.com:Alura071991"
            "arevaloisabel@hotmail.com:bernal17"
            "eliu1997@hotmail.com:Muraylo"
            "marcel.bize@hotmail.com:Andresitas" 
          )

          for user in "${users[@]}"; do
            email="${user%%:*}"
            name="${user##*:}"
            git config --global user.email "$email"
            git config --global user.name "$name"
            echo "Log entry by $name on $(date '+%Y-%m-%d %H:%M:%S')" >> contributors/log_${name}.txt
            git add contributors/log_${name}.txt
            git diff --cached --quiet || git commit -m "Log entry by $name"
            git push
          done
